//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declar
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Dec_Place { get; set; }
        public Nullable<System.DateTime> Dec_Date { get; set; }
        public byte[] Dec_App_Photo { get; set; }
        public byte[] Dec_App_Sign { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
