//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EduCourse
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string St_Ssc_Inst { get; set; }
        public Nullable<int> St_Ssc_Year { get; set; }
        public Nullable<decimal> St_Ssc_Per { get; set; }
        public string St_Ssc_Class { get; set; }
        public string St_Ssc_Money_Won { get; set; }
        public string St_Hsc_Inst { get; set; }
        public Nullable<int> St_Hsc_Year { get; set; }
        public Nullable<decimal> St_Hsc_Per { get; set; }
        public string St_Hsc_Class { get; set; }
        public string St_Hsc_Money_Won { get; set; }
        public string St_LD_Inst { get; set; }
        public Nullable<int> St_LD_Year { get; set; }
        public Nullable<decimal> St_LD_Per { get; set; }
        public string St_LD_Class { get; set; }
        public string St_LD_Money_Won { get; set; }
        public Nullable<int> St_Exam_Score { get; set; }
        public string St_College_Details { get; set; }
        public string St_City { get; set; }
        public string St_State { get; set; }
        public string St_District { get; set; }
        public Nullable<int> St_Pin_Code { get; set; }
        public string St_Country { get; set; }
        public string St_Admission_Status { get; set; }
        public string St_Univ_Name { get; set; }
        public string St_Univ_Person { get; set; }
        public string St_Course_Name { get; set; }
        public string St_Course_Appr { get; set; }
        public string St_Admsn { get; set; }
        public string St_Course_Cat { get; set; }
        public string St_Course_Type { get; set; }
        public Nullable<System.DateTime> St_Course_Start { get; set; }
        public Nullable<System.DateTime> St_Course_End { get; set; }
        public Nullable<int> St_Morat1 { get; set; }
        public Nullable<int> St_Morat2 { get; set; }
        public Nullable<int> St_Total_Morat { get; set; }
        public Nullable<int> St_Emi_Repay { get; set; }
        public Nullable<int> St_Loan_Period { get; set; }
        public string St_Int_Serv { get; set; }
        public Nullable<int> St_Exp_Income { get; set; }
        public string St_Clg_Name { get; set; }
        public string St_Course_Persuid { get; set; }
        public Nullable<System.DateTime> St_Compl_Date { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
