//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEduHome
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Org_Res_Own { get; set; }
        public string Org_Employment_Nat { get; set; }
        public string Org_Nat { get; set; }
        public string Org_Emp_Busi_Nat { get; set; }
        public string Org_Designation { get; set; }
        public string Org_Current_Year { get; set; }
        public string Org_Total_Year { get; set; }
        public string Org_Name { get; set; }
        public string Org_Address { get; set; }
        public Nullable<int> Org_Pin { get; set; }
        public string Org_City { get; set; }
        public string Org_State { get; set; }
        public string Org_Country { get; set; }
        public Nullable<int> Org_Phone { get; set; }
        public string Org_UAN { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
