//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpGold
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Ge_Occ_Type { get; set; }
        public string Ge_Org_Type { get; set; }
        public string Ge_Emp_Buss_Name { get; set; }
        public string Ge_Designation { get; set; }
        public Nullable<int> Ge_Curr_Work_Years { get; set; }
        public Nullable<int> Ge_Total_work_Years { get; set; }
        public Nullable<decimal> Ge_Net_Ann_Inc { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
