//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Prop_Type { get; set; }
        public string Prop_Trans_Type { get; set; }
        public string Prop_Builder_Name { get; set; }
        public string Prop_Project_Name { get; set; }
        public string Prop_Building_Name { get; set; }
        public Nullable<decimal> Prop_Land_Area { get; set; }
        public Nullable<decimal> Prop_Cost { get; set; }
        public string Prop_Addr { get; set; }
        public string Prop_Landmark { get; set; }
        public Nullable<int> Prop_Pin { get; set; }
        public string Prop_City { get; set; }
        public string Prop_State { get; set; }
        public string Prop_Country { get; set; }
        public string Prop_Ownership { get; set; }
        public string Prop_Seller_Name { get; set; }
        public string Prop_Seller_Addr { get; set; }
        public string Prop_Const_Stage { get; set; }
        public Nullable<decimal> Prop_Pur_Con_Cost { get; set; }
        public Nullable<decimal> Prop_Reg_Cost { get; set; }
        public Nullable<decimal> Prop_Total_Cost { get; set; }
        public Nullable<decimal> Prop_Stamp_Cost { get; set; }
        public Nullable<decimal> Prop_Other_Cost { get; set; }
        public Nullable<decimal> Prop_Own_Contrib { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
