//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanEdu
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<decimal> Edu_Tut_Fees { get; set; }
        public Nullable<decimal> Edu_Living_Expen { get; set; }
        public Nullable<decimal> Edu_Travel_Expen { get; set; }
        public Nullable<decimal> Edu_Other_Expen { get; set; }
        public Nullable<decimal> Edu_Total_Expen { get; set; }
        public Nullable<decimal> Edu_Own_Inc { get; set; }
        public Nullable<decimal> Edu_Scholar_Inc { get; set; }
        public Nullable<decimal> Edu_Other_Inc { get; set; }
        public Nullable<decimal> Edu_Loan_Required { get; set; }
        public string Edu_Disburs_Details { get; set; }
        public string Edu_Mode { get; set; }
        public string Edu_Dd_In_Favour_Of { get; set; }
        public string Edu_Payable_At_For { get; set; }
        public Nullable<decimal> Edu_DD_Amount { get; set; }
        public string Edu_Tt_Swift_Code { get; set; }
        public string Edu_Rtgs_Neft { get; set; }
        public string Edu_University_Ac { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
