//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class loandbEntities : DbContext
    {
        public loandbEntities()
            : base("name=loandbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Declar> Declars { get; set; }
        public virtual DbSet<EduAppDoc> EduAppDocs { get; set; }
        public virtual DbSet<EduCoDoc> EduCoDocs { get; set; }
        public virtual DbSet<EduCourse> EduCourses { get; set; }
        public virtual DbSet<EmpEduHome> EmpEduHomes { get; set; }
        public virtual DbSet<EmpGold> EmpGolds { get; set; }
        public virtual DbSet<Financial> Financials { get; set; }
        public virtual DbSet<GoldAppDoc> GoldAppDocs { get; set; }
        public virtual DbSet<Gstin> Gstins { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<HomeAppDoc> HomeAppDocs { get; set; }
        public virtual DbSet<LoanEdu> LoanEdus { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<Nominee> Nominees { get; set; }
        public virtual DbSet<Nri> Nris { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<PersonalAppDoc> PersonalAppDocs { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropGold> PropGolds { get; set; }
        public virtual DbSet<PropHome> PropHomes { get; set; }
        public virtual DbSet<PropPersonal> PropPersonals { get; set; }
        public virtual DbSet<PurpGold> PurpGolds { get; set; }
        public virtual DbSet<PurpPersonal> PurpPersonals { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
    }
}
