//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Nom_App_Name { get; set; }
        public string Nom_App_Addr { get; set; }
        public string Nom_Name { get; set; }
        public string Nom_Addr { get; set; }
        public string Nom_Relation { get; set; }
        public Nullable<int> Nom_Age { get; set; }
        public Nullable<System.DateTime> Nom_Dob { get; set; }
        public string Nom_Guar_Name { get; set; }
        public Nullable<int> Nom_Guar_Age { get; set; }
        public string Nom_Guar_Addr { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
