//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropGold
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<decimal> Gpr_Loan_Amount { get; set; }
        public Nullable<int> Gpr_Tenure_Months { get; set; }
        public Nullable<System.DateTime> Gpr_Payment_Date { get; set; }
        public string Gpr_Int_Pay_Mode { get; set; }
        public string Gpr_Disburs_Mode { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
