//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Ag_Prop_Type { get; set; }
        public string Ag_Prop_Classif { get; set; }
        public Nullable<int> Ag_Building_Age { get; set; }
        public Nullable<decimal> Ag_Market_Value { get; set; }
        public Nullable<decimal> Ag_Regis_Value { get; set; }
        public Nullable<decimal> Ag_Prop_Land_Area { get; set; }
        public Nullable<decimal> Ag_Buildup_Area { get; set; }
        public string Ag_Prop_Addr { get; set; }
        public string Ag_Landmark { get; set; }
        public Nullable<int> Ag_Pin { get; set; }
        public string Ag_City { get; set; }
        public string Ag_State { get; set; }
        public string Ag_Country { get; set; }
        public string Ag_Rev_Mortage { get; set; }
        public Nullable<decimal> Ag_Lumpsum_Amount { get; set; }
        public string Ag_Annuity_Periodicity { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
