//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurpGold
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Gpu_Purpose { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
