//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Ref_Name1 { get; set; }
        public string Ref_Relat1 { get; set; }
        public string Ref_Addr1 { get; set; }
        public Nullable<int> Ref_Pin1 { get; set; }
        public string Ref_City1 { get; set; }
        public string Ref_State1 { get; set; }
        public string Ref_Country1 { get; set; }
        public Nullable<long> Ref_Mob_Tel1 { get; set; }
        public string Ref_Email1 { get; set; }
        public string Ref_Name2 { get; set; }
        public string Ref_Relat2 { get; set; }
        public string Ref_Addr2 { get; set; }
        public Nullable<int> Ref_Pin2 { get; set; }
        public string Ref_City2 { get; set; }
        public string Ref_State2 { get; set; }
        public string Ref_Country2 { get; set; }
        public Nullable<long> Ref_Mob_Tel2 { get; set; }
        public string Ref_Email2 { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
