//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Personal_Applied { get; set; }
        public string Personal_Status { get; set; }
        public string Personal_Correction { get; set; }
        public string Home_Applied { get; set; }
        public string Home_Status { get; set; }
        public string Home_Correction { get; set; }
        public string Education_Applied { get; set; }
        public string Education_Status { get; set; }
        public string Education_Correction { get; set; }
        public string Gold_Applied { get; set; }
        public string Gold_Status { get; set; }
        public string Gold_Correction { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
